### ISSUE TITLE
ExtensionAttributes are all null

### ISSUE THREAD

**Issue by dakolta** [GruberMarkus/Set-OutlookSignatures#41] opened 2022-07-26 16:20 UTC
I have information in extended attributes and can see them using Microsofts Graph Explorer:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/18648939/181057857-651d99be-90e9-4a25-95a1-93511198f48c.png">

But when running the script they always come back empty
<img width="586" alt="Screen Shot 2022-07-26 at 9 14 53 AM" src="https://user-images.githubusercontent.com/18648939/181058579-842686a6-5346-4fa8-8620-729f194b1796.png">

I see that you had addressed the same issue earlier:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/18648939/181056522-26af6a46-5dc5-4734-ba2c-a5e6218a2fc4.png">

I am using the latest build from you, v3.2.0
This is happing on all users, I am at a standstill rolling this out, any help would be greatly appreciated.

**Comment by GruberMarkus** [comment] 2022-07-26 18:40
Thank you for finding and reporting this bug.

Please test [v3.2.1-beta1](https://github.com/GruberMarkus/Set-OutlookSignatures/releases/tag/v3.2.1-beta1) and let me know if the problem is solved.

For how many users do you plan to use Set-OutlookSignatures?

**Comment by dakolta** [comment] 2022-07-26 18:44
I am planning to use it on a small office of 10, but if everything is fine I will be using it on a client that has 100-150 users, plan on getting them to help sponsor this project.

**Comment by dakolta** [comment] 2022-07-26 18:57
Just tested it and the issue is fixed.

**Comment by GruberMarkus** [comment] 2022-07-26 20:59
Thanks for your feedback!
Commit 1d3b8d5fca36560ea282471f97db3082f0efc068, which is included in release [v3.2.1-beta1](https://github.com/GruberMarkus/Set-OutlookSignatures/releases/tag/v3.2.1-beta1) solves this issue.

Version 3.2.1 will probably be released in the next days.

If you have questions regarding sponsoring this project, please let me know.

**Closed by GruberMarkus** 2022-07-26 20:59 UTC
