### ISSUE TITLE
Issue with images not embedded

### ISSUE THREAD

**Issue by Imaginos** [GruberMarkus/Set-OutlookSignatures#28] opened 2022-01-06 10:36 UTC
Hi Markus
Happy new year to you !

I discovered an issue with the signatures using the embedded image param at $false.
In Outlook 2013, the signature appears correctly, if I open the htm file, I can see the picture too.
Here's the issue : 
- If I send from Outlook 2013, the recipients won't see the image (whatever they are using Outlook, web Outlook or even Gmail)
- If I send from the Web Outlook, it's OK

The issue appears event with the "Test all signature replacement variables.docx".

**Comment by GruberMarkus** [comment] 2022-01-06 10:40
Hi Thomas,

please send me the resulting signature ("test all signature replacement variables.htm" and the subfolder "test all signature replacement variables.files").

Does it only happen with the "test all signature replacement variables" template, or with self-created templates containing images, too?

**Comment by Imaginos** [comment] 2022-01-06 10:58
[test.htm.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/7821254/test.htm.txt)
Here's the file.

**Comment by GruberMarkus** [comment] 2022-01-06 11:25
I am missing the subfolder "test.files" containing the images.

Please also provide your source template file.

**Comment by Imaginos** [comment] 2022-01-06 12:43
[test.zip](https://github.com/GruberMarkus/Set-OutlookSignatures/files/7821838/test.zip)
Here we go

**Comment by GruberMarkus** [comment] 2022-01-06 13:26
Bug confirmed. Not only Outlook 2013 shows this behavior, but also newer versions: Images are shown in preview, but not sent with the e-mail, so the recipient only sees placeholders.

I am analyzing the root cause, which will probably take some days.


Assuming you have a French Windows and Office: When you manually create a signature with a picture in Outlook, what is the name of the automatically created subfolder containing the images?

**Comment by Imaginos** [comment] 2022-01-07 07:52
Well the folder containing images for test.htm is named test.files, Signature.htm has Signature.files

But, with Signature.files, another folder is created : Signature_fichiers, that contains 3 files : 
- colorschememapping.xml
- filelist.xml
- themedata.thmx
This folder is, of course copied in "My docs\Outlook signatures"

**Comment by GruberMarkus** [comment] 2022-01-07 09:43
Please perform the following steps and let me know the results:
1. Close Outlook
2. Create a new registry value "HKEY_CURRENT_USER\Software\Microsoft\Office\<Outlook version>\Outlook\Options\Mail\Send Pictures With Document" (32 bit DWORD) and set it to 1
3. Start Outlook
4. Send a new e-mail and check if the recipient now sees the image(s) from your signature

**Comment by GruberMarkus** [comment] 2022-01-07 09:52
Can i close this issue?

If yes, I will update Set-OutlookSignatures with an according hint to the registry key and the corresponding Microsoft support article.

**Comment by Imaginos** [comment] 2022-01-07 10:48
That's OK for me :)

Thanks again, Markus !

**Comment by GruberMarkus** [comment] 2022-01-07 16:36
@Imaginos, thank you for reporting this issue.

It is not a bug in Set-OutlokSignatures per se, but rather a default Outlook configuration that only has an effect when Set-OutlookSignatures' EmbedImagesInHTML parameter is set to false.

In commit e05341d64368f554cfcb8cb370594e1075026f18, the documentation for EmbedImagesInHTML has been updated with a link to the Microsoft support article https://support.microsoft.com/en-us/topic/inline-images-may-display-as-a-red-x-in-outlook-704ae8b5-b9b6-d784-2bdf-ffd96050dfd6 describing the problem and a solution.

This issue is closed as solved in accordance with the original creator @Imaginos.

**Closed by GruberMarkus** 2022-01-07 16:36 UTC
Labels: documentation
