### ISSUE TITLE
V3.6 and Office 2013 : issue with pictures and src value in htm file

### ISSUE THREAD

**Issue by Imaginos** [GruberMarkus/Set-OutlookSignatures#71] opened 2023-02-20 13:08 UTC
Hi Markus
Since version 3.6, I notice an issue on PC with Office 2013.

Templates are docx files.
With 2013, pictures are in a separate folder, "Signature.htm + Signature.files/"
Pictures are called in the htm file with the "src" attribute.
Here are the differences between src attribute in htm generated file:
- V3.51 : src="Signature.files/image002.png" 👍 
- V3.6  : src="1592677f-8f19-4360-81b3-83162ebdeefeHighRes_fichiers/image002.png" 👎 

Of course, there is no folder nammed 1592677f-8f19-4360-81b3-83162ebdeefeHighRes_fichiers
With Office 2016, pics are integrated in the htm file, so it's OK.

I had to roll back to v 3.51.

If you need more infos, just ask.

Regards
Tom

**Comment by GruberMarkus** [comment] 2023-02-20 14:27
Hi @Imaginos,

thanks for bringing up this issue.

The root cause has been found and corrected, the solution will be included in the v4.0.0 release.

**Closed** 2023-02-20 14:28 UTC
