### ISSUE TITLE
HTML template variables replacement not working

### ISSUE THREAD

**Issue by AnotherFranck** [GruberMarkus/Set-OutlookSignatures#87] opened 2023-09-29 13:35 UTC
Hi,
I am testing the last version of set-outlooksignature in order to migrate from the 3.6.
I have hopes that the signatures in outlook web are working since the new version of outlook is full web.
We are using only the html templates and generating only signatures.
When I try to use our own template for the signature, the variables inside are not replaced, even when testing with the "Test all default replacement variables.htm" delivered with the .zip.
Is the a specific way to configure the html templates now?
Thanks for your help.

**Comment by GruberMarkus** [comment] 2023-09-29 16:23
Hi @AnotherFranck,

thank you for reporting this issue!

We are already working on it, as a Benefactor Circle member has informed us about this issue just about a day ago.

The issue is related to a wrong RegEx string, and will be resolved in release v4.5.0. Release v4.5.0 will be published in the next days.


Regarding New Outlook (the Outlook for Windows app from the Microsoft store):
- Cloud roaming signatures are supported since v4.0.0
- New Outlook, which fully relies on cloud roaming signatures, is supported since v4.4.0
<br>
<br>
Please be aware that some features, including support for cloud roaming signatures, which are used by New Outlook, are only available for Benefactor Circle members. See '.\docs\Benefactor Circle' or https://explicitconsulting.at/open-source/set-outlooksignatures/ for details.
<br>
<br>
I will keep this issue open until the new version is released and you confirm that HTM templates are processed correctly.

**Comment by GruberMarkus** [comment] 2023-09-29 16:39
If you are interested in testing the new version before it is release, please let me know and send your mail address.

**Comment by GruberMarkus** [comment] 2023-09-29 18:57
Sometimes things happen faster than expected...

Release v4.5.0 has been published, containing a fix for this issue.

If the problem persists, please create a new issue or re-open this one.

**Closed by GruberMarkus** 2023-09-29 18:57 UTC

**Comment by AnotherFranck** [comment] 2023-10-02 06:14
Thanks for update Markus!
