### ISSUE TITLE
$CURRENTUSERTELEPHONE$ not being populated from graph

### ISSUE THREAD

**Issue by vitorpereira** [GruberMarkus/Set-OutlookSignatures#26] opened 2021-12-19 12:37 UTC
Using v2.4.0 and $CURRENTUSERTELEPHONE$ is not being populated using -graphonly $true. Checked using graph explorer and can see the value for the test user as per below. No errors when running.

"businessPhones": [
        "+44 1234567890 x123"
    ]

**Comment by GruberMarkus** [comment] 2021-12-19 13:48
Thanks for finding and reporting this error!

Please test if changing a line in '.\docs\default graph config.ps1' solves the problem in your environment, too:
Old line:     telephonenumber            = 'businessPhones[0]'
new line:     telephonenumber            = 'businessPhones'


If you confirm the fix, I will release v2.4.1 as fast as I can.

**Comment by vitorpereira** [comment] 2021-12-19 14:43
I've done that and from the messages I see when running it, I'm now getting values for $CURRENTMAILBOXMANAGERTELEPHONE$, $CURRENTMAILBOXTELEPHONE$ and $CURRENTUSERMANAGERTELEPHONE$ but not for $CURRENTUSERTELEPHONE$.

**Comment by GruberMarkus** [comment] 2021-12-19 15:08
It's working fine in my cloud environment:
$CURRENTMAILBOXMANAGERTELEPHONE$: ManagerOfficePhone
$CURRENTMAILBOXTELEPHONE$: OfficePhone
$CURRENTUSERMANAGERTELEPHONE$: ManagerOfficePhone
$CURRENTUSERTELEPHONE$: OfficePhone

Please save the full output of Set-OutlookSignatures as text file and add it to this issue for further analysis.

**Comment by GruberMarkus** [comment] 2021-12-21 16:29
Hi Vitor,

any updates from you side?

It's working fine in my cloud environment:
$CURRENTMAILBOXMANAGERTELEPHONE$: ManagerOfficePhone
$CURRENTMAILBOXTELEPHONE$: OfficePhone
$CURRENTUSERMANAGERTELEPHONE$: ManagerOfficePhone
$CURRENTUSERTELEPHONE$: OfficePhone

**Comment by GruberMarkus** [comment] 2021-12-22 14:11
Hi Vitor,

v2.5.0-beta1 has just been released. It contains some new features and a fix for the problem in this issue.

Please let me know if this beta solves the problem (if yes, I will close this issue).

**Comment by GruberMarkus** [comment] 2021-12-24 14:28
Hi @vitorpereira,

Merry Christmas!

v2.5.0-beta1 has been released, containing a fix for the problem in this issue.

Please let me know if I can close this issue as solved.

**Comment by GruberMarkus** [comment] 2022-01-03 08:27
Closing, as this bug has been confirmed and solved in v2.5.0-beta1.

The original issue creator, @vitorpereira, is unavailable since 15 days. He can re-open this issue any time should he finds that the bug has not been solved to his expectation.

**Closed by GruberMarkus** 2022-01-03 08:27 UTC
Labels: bug
